### ISSUE TITLE
Possible enhacements

### ISSUE THREAD

**Issue by jbonor** [cconard96/glpi-webresources-plugin#1]
Hi, I am testing you plugin and I would like to propose some changes that I think would make it more easy to use.

- I've spent several minutes looking for a way to edit the resources that I have created. I did'nt expect it to be "under" the looking glass. I think it would be better to move the configuration of the resource to the "configuration" or "administration" menu in line with other plugins.
- It was not evident for me at least how to define a favicon or icon for a resource. It would be nice to have some indications on screen or even a way to retrieve the default favicon from the URL like other applications do.
- A preview mode of the icon/text would be cool.

Best regards.

**Comment by cconard96** [comment]
1. There may be a better way to present that but I wasn't sure given some limitations with the GLPI menu system, and I really wanted to avoid have two different menu options (one for the dashboard and one for admin). I hope it is a good short-term solution, but I've started adding to the Wiki in this repository and added a Quick Start to it and linked to it from the README.
2. I hope the preview mode reduces some confusion about that. I'm not sure about automatically filling the `icon` field with the favicon link is a good solution. While a lot of sites have it at '/favicon.ico' relative to their root domain (such as https://github.com/favicon.ico), it is not required and the plugin would have to download the content of the supplied URL, parse the HTML, and find the meta tag that specifies the icon location. I'm not discounting this possibility, but I need to think about it more. I think if I add it, I should add the ability get the highest quality icon (You can define multiple icons like the apple-touch icons and a few other specialized ones). I would rather find a good solution that is already built than trying to implement something custom here.
3. I just added a preview mode to the master branch. It will be included in version 1.1.0.

**Comment by cconard96** [comment]
Retrieval of a default icon was added in #3. It will be included in version 1.1.0.
This next version of the plugin will be release this weekend.
