### ISSUE TITLE
Location of menu item

### ISSUE THREAD

**Issue by hgpit** [cconard96/glpi-webresources-plugin#10]
Hey,

We just installed this plugin to have a play, and find it quite useful for our environment.

Two questions/requests though:

1. Is there any way we can move the 'Web Resources' menu item to something like GLPI's existing 'Tools' menu? It seems a shame to create a whole new menu just for this one item.
2. How can we stop the presentation of our own icons from stretching out of proportion? is it possible to retain the aspect ratio of the icons?

Thanks! :)

**Comment by cconard96** [comment]
The Plugins menu technically already exists in GLPI without any plugins, its just hidden unless something is in it. It doesn't look like any plugins beyond my own use this menu though.
To change it, you need to change this line in setup.php:
$PLUGIN_HOOKS['menu_toadd']['webresources'] = ['plugins' => 'PluginWebresourcesDashboard'];
to:
$PLUGIN_HOOKS['menu_toadd']['webresources'] = ['tools' => 'PluginWebresourcesDashboard'];
You may need to log out and back in to regenerate the menu.
Then to fix the breadcrumb links, check the files in the plugin's front folder and look for lines calling `Html::header`. You will need to change the option "plugins" to "tools" as well.

I'm not sure about the second point yet. I found a potential bug with create resources so I am going to fix that first today and then look at the image issue. Can you attach a screenshot of what is doing with your icons?

**Comment by hgpit** [comment]
Hey Curtis,

Thank you so much for your response :)

I will have a play changing the menu location a little later - but that sounds great!

In regards to the icons, as an example we have added these via your plugin:
![image](https://user-images.githubusercontent.com/16598973/104038581-34264180-51cd-11eb-8a28-d3d64b79b43c.png)

But, on our intranet (which is what we're trying to replicate within GLPI), the icons retain their aspect ratio (the 'Progress' icon probably makes it most obvious):

![image](https://user-images.githubusercontent.com/16598973/104038865-86676280-51cd-11eb-882e-38503b94cfa1.png)

Hopefully this makes sense :)

**Comment by hgpit** [comment]
Menu item change worked a treat, by the way; thanks! :)

**Comment by cconard96** [comment]
For icon scaling, can you test the changes done in #11?
The pull request gets rid of some unneeded files as well but you can test by only making the changes done in the `css/webresources.scss` and `setup.php` files.
In addition to the icon scaling, it also adds a bit more space between resources so they don't feel as cramped.
Some better layout options may come in the next feature update.

**Comment by hgpit** [comment]
Hi Curtis,

I will test the changes this afternoon, thanks!

We have just noticed, that moving the 'Web Resources' menu item from 'Plugins' to the 'Tools' menu appears to break/prevent the appearance of the add and search edit functions of the plugin. We have double-checked the GLPI user privileges.

For example, when using the default (unpreferred) menu location:
![image](https://user-images.githubusercontent.com/16598973/104454314-93090380-559d-11eb-8dbb-3d4d89c25e0b.png)

After moving the menu item to appear under 'Tools' (same user):
![image](https://user-images.githubusercontent.com/16598973/104454493-d7949f00-559d-11eb-8d9b-63828b9b3a78.png)

Not sure if there would be an easy fix, or whether it would be a bit fiddly to deal with?

Thank you.

**Comment by hgpit** [comment]
The change regarding SCSS, icons etc is working fine 👍 
![image](https://user-images.githubusercontent.com/16598973/104458278-0b25f800-55a3-11eb-8743-6fdfc5e23141.png)

Thank you so much!

**Comment by cconard96** [comment]
> Hi Curtis,
> 
> I will test the changes this afternoon, thanks!
> 
> We have just noticed, that moving the 'Web Resources' menu item from 'Plugins' to the 'Tools' menu appears to break/prevent the appearance of the add and search edit functions of the plugin. We have double-checked the GLPI user privileges.
> 
> For example, when using the default (unpreferred) menu location:
> ![image](https://user-images.githubusercontent.com/16598973/104454314-93090380-559d-11eb-8dbb-3d4d89c25e0b.png)
> 
> After moving the menu item to appear under 'Tools' (same user):
> ![image](https://user-images.githubusercontent.com/16598973/104454493-d7949f00-559d-11eb-8d9b-63828b9b3a78.png)
> 
> Not sure if there would be an easy fix, or whether it would be a bit fiddly to deal with?
> 
> Thank you.

This is most likely just a cache issue if you already changed the headers in the `front/` files.
 - front/dashboard.php
 - front/resource.form.php
 - front/resource.php
Logging out and back in should have resolved that problem though.

**Comment by hgpit** [comment]
Ha, sorry, I completely missed the necessity to change the additional files for the menu change. All good :)

**Comment by cconard96** [comment]
The menu location is now configurable with the changes made in pull request #12. Could you test this?
It will be in the next feature release (1.4.0) if it works well for you.
