### ISSUE TITLE
Can't see config option for changing menu location

### ISSUE THREAD

**Issue by hgpit** [cconard96/glpi-webresources-plugin#25]
![image](https://user-images.githubusercontent.com/16598973/155300735-962cfd27-755f-47ca-9e9f-b3a776a99503.png)

Where exactly is this config option, please?

We're using v1.3.2 of the plugin and GLPI 9.5.7.

Thanks.

**Comment by cconard96** [comment]
It is under the Setup > General menu option and then in its own "Web Resources" tab. Most plugin configuration options are put here.
