### ISSUE TITLE
Autocompletion feature has been removed

### ISSUE THREAD

**Issue by WebGregGit** [cconard96/glpi-webresources-plugin#32]
**Describe the bug**
PHP User deprecated function (16384): Autocompletion feature has been removed. in /var/www/html/glpi/src/Toolbox.php at line 571

**To Reproduce**
1. Go to 'Plugins' > Web Resources
2. Click on 'Add' button
3. Here is the error.

**System Specifications (please complete the following information):**
 - GLPI 10.0.4
 - Server Version: 8.0.31-0ubuntu0.20.04.1
 - PHP 7.4.3
 - Web Resources                  Version: 2.0.2

**Additional context**
[https://github.com/glpi-project/glpi/issues/11554](https://github.com/glpi-project/glpi/issues/11554)

**Comment by cconard96** [comment]
Fixed by #33
