### ISSUE TITLE
When not able to resolve the favicon path, a broken page appears (enhancement)

### ISSUE THREAD

**Issue by raregtp** [cconard96/glpi-webresources-plugin#4]
When not able to resole the favicon path, the link still works but the graphic appears to be "broken".  While I get it's not, and is just the way the icon is being subbed, would it be possible have an option to fall back on a "color" icon?

Below is what I see:

![image](https://user-images.githubusercontent.com/16689744/88843716-2e9ce800-d1a7-11ea-9bf2-5acac8e46e2e.png)

I would propose replacing no-retrievable icons with something like this:

![image](https://user-images.githubusercontent.com/16689744/88843816-555b1e80-d1a7-11ea-8c5c-23b841591b31.png)

Thanks!

**Comment by cconard96** [comment]
Was the favicon broken when the resource was created, or afterwards?

**Comment by raregtp** [comment]
The situation presented itself when I put in resources that are in another subnet which is not reachable when I'm on a VPN into the office.  Due to security reasons I can't expose that subnet through our VPN, so any resources I point to that subnet will show up like this when remote.  Just figured making it cleaner in these types of situations would be better.  Thoughts?

**Comment by cconard96** [comment]
The changes made in the linked PR adds a fallback to the generic Chrome icon when the image fails to load.
